"""create user category table

Revision ID: b7b3a46c20b2
Revises:
Create Date: 2025-09-06 17:07:12.891345

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7b3a46c20b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "race",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "IN_PROGRESS", "FINISHED", name="race_state"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="race_visibility"),
            nullable=False,
        ),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=36), nullable=False),
        sa.Column("hashed_password", sa.String(length=1000), nullable=False),
        sa.Column("race_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["race.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("race")
    # ### end Alembic commands ###
